version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: finance-control-db
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance-control-db
      MYSQL_USER: chi-user
      MYSQL_PASSWORD: chi-pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: